import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js練習用</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        Next.js練習用
        </h1>

        <p>
          githubとVarcle連結させてみた
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://borderlesss.net/"
          target="_blank"
          rel="noopener noreferrer"
        >
          borderlesss
        </a>
      </footer>
    </div>
  )
}
